go
use QLCB
go

--Q1
select distinct NHANVIEN.MANV,NHANVIEN.TEN,NHANVIEN.DCHI,NHANVIEN.DTHOAI from NHANVIEN,PHANCONG,LICHBAY where NHANVIEN.MANV=PHANCONG.MANV and PHANCONG.MACB=LICHBAY.MACB and LICHBAY.MALOAI='B747' and NHANVIEN.LOAINV=1
--Q2
select CHUYENBAY.MACB, LICHBAY.NGAYDI from CHUYENBAY, LICHBAY where CHUYENBAY.SBDI = 'DCA' and CHUYENBAY.MACB = LICHBAY.MACB and CHUYENBAY.GIODI between '14:00' and '16:00'
--Q3
select distinct NHANVIEN.TEN from NHANVIEN,PHANCONG,CHUYENBAY where NHANVIEN.MANV=PHANCONG.MANV and PHANCONG.MACB='100' and CHUYENBAY.MACB='100' and CHUYENBAY.SBDI='SLC'
--Q4
select distinct LICHBAY.MALOAI,LICHBAY.SOHIEU from CHUYENBAY,LICHBAY where CHUYENBAY.SBDI='MIA' and CHUYENBAY.MACB=LICHBAY.MACB
--Q5
select CHUYENBAY.MACB,DATCHO.NGAYDI,KHACHHANG.TEN,KHACHHANG.DCHI,KHACHHANG.DTHOAI from KHACHHANG,CHUYENBAY,DATCHO where DATCHO.MAKH=KHACHHANG.MAKH and DATCHO.MACB=CHUYENBAY.MACB ORDER BY DATCHO.MACB, DATCHO.NGAYDI DESC
--Q6
select CHUYENBAY.MACB,PHANCONG.NGAYDI,NHANVIEN.TEN,NHANVIEN.DCHI,NHANVIEN.DTHOAI from NHANVIEN,CHUYENBAY,PHANCONG where PHANCONG.MANV=NHANVIEN.MANV and PHANCONG.MACB=CHUYENBAY.MACB ORDER BY PHANCONG.MACB, PHANCONG.NGAYDI DESC
--Q7
select CHUYENBAY.MACB,PHANCONG.NGAYDI,NHANVIEN.MANV,NHANVIEN.TEN from NHANVIEN,CHUYENBAY,PHANCONG where PHANCONG.MANV=NHANVIEN.MANV and PHANCONG.MACB=CHUYENBAY.MACB and CHUYENBAY.SBDEN='ORD'
--Q8
select PHANCONG.MACB,PHANCONG.NGAYDI,NHANVIEN.TEN from NHANVIEN,PHANCONG where PHANCONG.MANV=NHANVIEN.MANV and NHANVIEN.MANV='1001'
--Q9
select CHUYENBAY.MACB,CHUYENBAY.SBDI,CHUYENBAY.GIODEN, CHUYENBAY.GIODI, LICHBAY.NGAYDI from CHUYENBAY, LICHBAY where CHUYENBAY.SBDEN = 'DEN' and CHUYENBAY.MACB = LICHBAY.MACB ORDER BY CHUYENBAY.SBDI, LICHBAY.NGAYDI DESC
--Q10
select NHANVIEN.TEN,LOAIMB.HANGSX,LOAIMB.MALOAI from NHANVIEN,KHANANG,LOAIMB where NHANVIEN.MANV=KHANANG.MANV and KHANANG.MALOAI = LOAIMB.MALOAI and NHANVIEN.LOAINV=1
--Q11
select distinct NHANVIEN.MANV,NHANVIEN.TEN from NHANVIEN,LICHBAY where LICHBAY.NGAYDI='11-01-2000' and LICHBAY.MACB='100' and NHANVIEN.LOAINV=1
--Q12
select distinct CHUYENBAY.MACB,NHANVIEN.MANV,NHANVIEN.TEN from NHANVIEN,CHUYENBAY,LICHBAY where LICHBAY.NGAYDI='10/31/2000' and CHUYENBAY.SBDI='MIA' and CHUYENBAY.GIODI = '20:30'
--Q13
select LICHBAY.MACB,LICHBAY.SOHIEU,LICHBAY.MALOAI,LOAIMB.HANGSX from NHANVIEN,PHANCONG,LICHBAY,LOAIMB where NHANVIEN.MANV=PHANCONG.MANV and NHANVIEN.TEN='Quang' and PHANCONG.MACB=LICHBAY.MACB and LICHBAY.MALOAI=LOAIMB.MALOAI and NHANVIEN.LOAINV=1
--Q14
select NHANVIEN.TEN from NHANVIEN where NHANVIEN.LOAINV=1 and not exists (select * from PHANCONG where NHANVIEN.MANV = PHANCONG.MANV)
--Q15
select distinct KHACHHANG.TEN from KHACHHANG,DATCHO,LOAIMB,LICHBAY where KHACHHANG.MAKH=DATCHO.MAKH and DATCHO.MACB=LICHBAY.MACB and LOAIMB.MALOAI=LICHBAY.MALOAI and LOAIMB.HANGSX='Boeing'
--Q16
select distinct MACB from LICHBAY where SOHIEU='10' and MALOAI='B747'