go
use QLCB
go

--Q17
select CHUYENBAY.SBDEN, count(CHUYENBAY.MACB) as N'Số lượng chuyến bay'
from CHUYENBAY
group by CHUYENBAY.SBDEN
order by CHUYENBAY.SBDEN asc
--Q18
select CHUYENBAY.SBDI, count(CHUYENBAY.MACB) as N'Số lượng chuyến bay'
from CHUYENBAY
group by CHUYENBAY.SBDI
order by CHUYENBAY.SBDI asc
--Q19
select CHUYENBAY.SBDI,LICHBAY.NGAYDI,count(CHUYENBAY.MACB) as N'Số lượng'
from CHUYENBAY, LICHBAY
where CHUYENBAY.MACB=LICHBAY.MACB
group by CHUYENBAY.SBDI,LICHBAY.NGAYDI
--Q20
select CHUYENBAY.SBDEN,LICHBAY.NGAYDI,count(CHUYENBAY.MACB) as N'Số lượng'
from CHUYENBAY, LICHBAY
where CHUYENBAY.MACB=LICHBAY.MACB
group by CHUYENBAY.SBDEN,LICHBAY.NGAYDI
--Q21
select LICHBAY.MACB,LICHBAY.NGAYDI,count(NHANVIEN.MANV) as N'Số lượng nhân viên'
from PHANCONG, LICHBAY, NHANVIEN
where PHANCONG.MACB=LICHBAY.MACB and PHANCONG.MANV=NHANVIEN.MANV and NHANVIEN.LOAINV=1
group by LICHBAY.MACB,LICHBAY.NGAYDI
--Q22
select CHUYENBAY.SBDI,count(CHUYENBAY.MACB) as N'Số lượng chuyến bay'
from LICHBAY, CHUYENBAY
where LICHBAY.MACB=CHUYENBAY.MACB and LICHBAY.NGAYDI='11/01/2000' and CHUYENBAY.SBDI='MIA'
group by CHUYENBAY.SBDI
--Q23
select LICHBAY.MACB,LICHBAY.NGAYDI,count(distinct PHANCONG.MANV) as N'Số lượng nhân viên'
from LICHBAY, PHANCONG
where LICHBAY.MACB=PHANCONG.MACB and LICHBAY.NGAYDI=PHANCONG.NGAYDI
group by LICHBAY.MACB,LICHBAY.NGAYDI
order by count(distinct PHANCONG.MANV) desc
--Q24
select LICHBAY.MACB,LICHBAY.NGAYDI,count(distinct DATCHO.MAKH) as N'Số lượng khách hàng'
from LICHBAY, DATCHO
where LICHBAY.MACB=DATCHO.MACB and LICHBAY.NGAYDI=DATCHO.NGAYDI
group by LICHBAY.MACB,LICHBAY.NGAYDI
order by count(distinct DATCHO.MAKH) desc
--Q25
select PHANCONG.MACB,PHANCONG.NGAYDI,sum(distinct NHANVIEN.LUONG) as N'Tổng lương'
from PHANCONG,NHANVIEN
where PHANCONG.MACB=PHANCONG.MACB
group by PHANCONG.MACB,PHANCONG.NGAYDI
order by count(distinct NHANVIEN.LUONG) asc
--Q26
select avg(distinct NHANVIEN.LUONG) as N'Lương trung bình'
from NHANVIEN
where NHANVIEN.LOAINV=0
--Q27
select avg(distinct NHANVIEN.LUONG) as N'Lương trung bình'
from NHANVIEN
where NHANVIEN.LOAINV=1
--Q28
select LICHBAY.MALOAI,count(LICHBAY.MACB) as N'Số lượng chuyến bay'
from LICHBAY,CHUYENBAY
where LICHBAY.MACB=CHUYENBAY.MACB and CHUYENBAY.SBDEN='ORD'
group by LICHBAY.MALOAI
--Q29
select CHUYENBAY.SBDI,count(CHUYENBAY.MACB) as N'Số lượng'
from CHUYENBAY
where CHUYENBAY.GIODI between '10:00' and '22:00'
group by CHUYENBAY.SBDI
--Q30
select NHANVIEN.TEN,count(PHANCONG.MACB) as N'Số lượng'
from PHANCONG,NHANVIEN,LICHBAY
where NHANVIEN.MANV=PHANCONG.MANV and PHANCONG.NGAYDI=LICHBAY.NGAYDI and PHANCONG.MACB=LICHBAY.MACB and NHANVIEN.LOAINV=1
group by NHANVIEN.TEN,PHANCONG.NGAYDI
having count(PHANCONG.MACB)>=2
--Q31
select LICHBAY.MACB,LICHBAY.NGAYDI,count(DATCHO.MAKH) as N'Số lượng'
from DATCHO,LICHBAY
where DATCHO.NGAYDI=LICHBAY.NGAYDI and DATCHO.MACB=LICHBAY.MACB
group by LICHBAY.MACB,LICHBAY.NGAYDI
having count(DATCHO.MAKH)<3
--Q32
select LICHBAY.MALOAI,LICHBAY.SOHIEU,count(*) as N'Số lượng'
from PHANCONG,LICHBAY
where PHANCONG.NGAYDI=LICHBAY.NGAYDI and PHANCONG.MACB=LICHBAY.MACB and PHANCONG.MANV='1001'
group by LICHBAY.MALOAI,LICHBAY.SOHIEU
having count(*)>2
--Q33
select HANGSX, count(*)
from LOAIMB
group by HANGSX